# Generated by Django 3.2.9 on 2021-12-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250)),
                ('shortUrl', models.CharField(max_length=30, unique=True)),
                ('premiumType', models.BooleanField()),
                ('exp_date', models.DateTimeField(null=True)),
                ('visited', models.IntegerField(null=True)),
            ],
        ),
    ]
